name: Run Docker App

on:
  workflow_dispatch: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            #docker pull sundoc14/movies:latest
            #docker stop mov1 || true
            #docker rm mov1 || true
            docker run -d -p 8080:80 --memory=512m --memory-swap=1g --restart always sundoc14/movies:latest
