name: Control Panel

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select workflow to run"
        required: true
        type: choice
        options:
          - Build & Push
          - run-app
          - stop-all

jobs:

  build-deploy:
    if: ${{ github.event.inputs.action == 'build-deploy' }}
    uses: ./.github/workflows/Build&Push.yml

  run-app:
    if: ${{ github.event.inputs.action == 'run-app' }}
    uses: ./.github/workflows/run.yml

  stop-all:
    if: ${{ github.event.inputs.action == 'stop-all' }}
    uses: ./.github/workflows/stop-all.yml
