name: Docker app deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select action"
        required: true
        type: choice
        options:
          - Build and Deploy Docker to Azure VM 
          - Run Docker App 
          - Stop all containers 

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Run selected action
        run: |
          case "${{ github.event.inputs.action }}" in
            build)
              echo "Building Pushing image"
              ;;
            deploy)
              echo "Deploying container"
              ;;
            restart)
              echo "Clearing container"
              ;;
          esac
