- name: SSH Deploy
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.VM_HOST }}
    username: ${{ secrets.VM_USER }}
    key: ${{ secrets.VM_SSH_KEY }}
    script: |
      echo "Connected"
      hostname
